### ISSUE TITLE
Screenshots til readme

### ISSUE THREAD

**Issue by andracs** [ZealandNaestved/DAT20-UP-projekt#228]
Jeg har set, at Jeres mockup har gode skærmbilleder. 

Det er på tide, at vise nogle af disse frem i projektets beskrivelse af Readme.

Måske kan det også omskrives liddt, så det kommunikerer til 1) andre udviklere 2) kommende slutbrugere. (Hvad kan programmet? Hvordan virker den? Hvorfor udvikles den og hvem kan få gavn af det GENERELT (udover høk)?

**Comment by AsHuOvSo** [comment]
Under 'Vejledning til programmet' -> Brugerinterface:
Ret ui til UI.
Nøgleord skal skrive med stort efter punktum

Vareforbrug:
Ret 'dette' til stort D efter punktum.
Ret 'derefter' til stort D efter punktum.

Øvrige kapacitetsomkostninger:
Ret til et ord
Del op. En lang sætning på 4 linjer er uoverskueligt.

Afskrivninger:
'Vider salg' skal rettes til videresalg

Kort gennemgang:
I anden sætning skal 'har vi' eller 'er der' slettes.
Imellem billede 1 og billede 2 skal 'Intjeningsbidrag' rettes til 'Indtjeningsbidrag'
I sidste linje skal 'efter' erstattes af 'af' og alt efter 'udregninger' skal slettes.

Det var de anslags/stavefejl jeg lige lagde mærke til
