### ISSUE TITLE
Testmappen mangler lidt kærlighed

### ISSUE THREAD

**Issue by andracs** [ZealandNaestved/DAT20-UP-projekt#229]
Dokumenterne i testmappen mangler lidt opdateringer, flere af dem har TODO's i sig.

**Comment by LouiseFuglsang** [comment]
Hej András
Jeg kan se at der mangler Test til UC1, UC2 og UC4. To af testene dækker hele programmet, skal jeg reviewe dem og bede dem lave det om så det passer til kun en use case i stedet for hele programmet? Eller er det lige meget så langt henne i forløbet (testene er jo udført med brugerne).

**Comment by andracs** [comment]
Jeg tænker, at da det er en øvelse, så vil det nok være en god idé at reviewe og rette. God dag :)

**Comment by andracs** [comment]
Kan du nappe denne i dag, @LouiseFuglsang ? Dvs. reviewe og bede dem lave, så det passer?

**Comment by LouiseFuglsang** [comment]
Done

**Comment by andracs** [comment]
@LouiseFuglsang - Det var godt :) Så kan du vel lukke issuet, ikke?

**Comment by LouiseFuglsang** [comment]
Ikke før den pågældende har rettet det til som jeg har bedt om.
Jeg lukkede issuet, men åbnede det igen, da jeg fik at vide at det er sådan vi gør i denne uge (var syg da det blev aftalt).

**Comment by LouiseFuglsang** [comment]
Men jo, jeg har jo oprettet to nye issues med rettelserne, så jeg lukker denne :)
