### ISSUE TITLE
Tilrettelse af testcase for Use case 4

### ISSUE THREAD

**Issue by LouiseFuglsang** [ZealandNaestved/DAT20-UP-projekt#256]
Hej Mikkel og Anders

András har bedt om at test casene bliver rettet til, selv om de er overstået.

I skal derfor rette nedenstående til kun at gælde for Use Case 4:

https://github.com/ZealandNaestved/DAT20-UP-projekt/blob/main/05%20Test/Test03_Testcases.md

Mvh. Jenna og Louise

**Comment by Mewmewww** [comment]
Synes igen det er smukt ændret.
