### ISSUE TITLE
Tilrettelse af testcase for use case 2

### ISSUE THREAD

**Issue by LouiseFuglsang** [ZealandNaestved/DAT20-UP-projekt#257]
Hej  igen Anders

Som skrevet før har András bedt om at test casene bliver rettet til, selv om de er overstået.

Du skal derfor rette nedenstående til kun at gælde for Use Case 2:

https://github.com/ZealandNaestved/DAT20-UP-projekt/blob/main/05%20Test/Test02_Kundem%C3%B8de1.md

Mvh. Jenna og Louise

**Comment by Mewmewww** [comment]
Ser fornuftigt ud.
